### ISSUE TITLE
Testing of alternative Renderers

### ISSUE THREAD

**Issue by manuelroth** [geometalab/osm2vectortiles#13]
- Tilelive https://github.com/mapbox/tilelive
- Tessera https://github.com/mojodna/tessera
- Avecado https://github.com/MapQuest/avecado

Check also projects linked from:
https://github.com/mapbox/awesome-vector-tiles

Especially:
https://github.com/vross/vector-tiles-producer

**Comment by klokan** [comment]
One more, which looks promising, is developed by people around Wikipedia Maps Tile Server. See and test:
https://github.com/kartotherian/kartotherian and
https://github.com/wikimedia/maps-tilerator
