### ISSUE TITLE
OSM Database Import

### ISSUE THREAD

**Issue by lukasmartinelli** [geometalab/osm2vectortiles#18]
Use imposm3 and PostGIS to create a reproducable database container from OSM planet files.
The whole import process should be automated.

The tm2source project can then connect to the database and generate the vector tiles.

**Comment by sfkeller** [comment]
We're using osm2pgsql. Did you evaluate that versus imposm3?
In case you stick with imposm3 I'd recommend to use option "osm2pgsql schema compatibility".
