### ISSUE TITLE
OSX Postgres image can not mount volumes

### ISSUE THREAD

**Issue by manuelroth** [geometalab/osm2vectortiles#22]
-> https://github.com/docker-library/postgres/issues/60

Workaround:
- Start database Docker directly inside virtualbox

**Comment by lukasmartinelli** [comment]
We cannot fix that ourselves. The official Postgres image needs to fix that. It is a bit cumbersome for development but because most people will never execute the import step (as it requires huge infrastructure) it is not that bad if it only runs nice on Linux.
