### ISSUE TITLE
Tileserver: Tessera serve vector tiles directly to clients like Mapbox Studio

### ISSUE THREAD

**Issue by manuelroth** [geometalab/osm2vectortiles#24]
Another thing about tessera. It does not serve `pbf` files directly to clients like e.g. Mapbox Studio or Mapbox GL. This should be added in the future as well.

**Comment by lukasmartinelli** [comment]
Created an issue at the tessera project.
https://github.com/mojodna/tessera/issues/30

**Comment by lukasmartinelli** [comment]
I think we should move this feature into the `STABLE` milestone and focus entirely on getting the source style and vector tiles produced in `BETA` milestone.

Tileserver PHP works quite wonderful with serving the vector tiles to MapboxStudio, I think of including it in the vectortile server just for the nice display and serving the PBFs to Mapbox Studio. This means the Docker image will get a bit fatter.

The rendering would be taken over by tessera (with an Apache redirect rule like the one that is used to redirect to the filesystem).

One architecture I would fancy:

![tileserver](https://cloud.githubusercontent.com/assets/1288339/10447413/772158be-7184-11e5-9863-c5b3d1858438.png)

**Comment by klokan** [comment]
+1
