### ISSUE TITLE
OSM Bright Source: Add data.xml Mapnik XML Version in addition to the data.yml version

### ISSUE THREAD

**Issue by manuelroth** [geometalab/osm2vectortiles#27]
- If we want to generate mbtiles from command line, we need the Mapnik XML version
```
tilelive-copy --bounds=-180,-85,180,85 bridge:///home/mapbox/tmp/project.tm2source/data.xml mbtiles:///tmp/out.mbtiles
```

**Comment by lukasmartinelli** [comment]
When using the `tmsource` tilelive provider whe do not need the Mapnik `data.xml`.
https://github.com/mojodna/tilelive-tmsource

**Comment by klokan** [comment]
Note: In case the XML would be required from a C/C++ binding this is the function for conversion:
https://github.com/mojodna/tilelive-tmsource/blob/master/index.js#L143
