### ISSUE TITLE
MBTiles generation performance

### ISSUE THREAD

**Issue by lukasmartinelli** [geometalab/osm2vectortiles#29]
First goal is to export the MBTiles for the world once. Then we can measure and improve and worry about performance.

Comment from Petr for this topic:

> I believe that if we can get rid of HTTP and crawling of the tiles from localhost web-server, and instead call the mapnik library directly (in a way like: https://github.com/vross/vector-tiles-producer (with $ xargs command) or equivalent made in python (with multiprocessing) the tile generation could be quite fast, and could very well saturate the single installation of Postgres on a powerful machine with the vertical parallelisation.

> If the styles are tweaked to render from z0 down to z14 - which is mentioned in the MapBox presentations (!!!), then the world rendering could be split into tasks working on "metapyramids" with each tasks doing for example 5 zoom-levels bellow a single tile (z0: 1x1, z1: 2x2, z2: 4x4, z3: 8x8, z4: 16x16) - with tasks in groups on one of the 3 floors (z0-z4, z5-z9, z10-z15).
 
> In such case you have 1 million of tasks to do (1 task for zooms 0-4 + 256 tasks for zooms 5-9 + the rest for zooms 10-15)
where each tasks must do 341 tiles (1 + 4 + 16 + 64 + 256).

> To render cca 358 millions of tiles (1 + 4 + 16 + 64 + 256 + 1024 + 4096 + 16384 + 65536 + 262144 + 1048576 + 4194304 + 16777216 + 67108864 + 268435456 = 357913941) you could start the tasks with defined parallelism.

> The metapyramid may be more efficient bigger, but then you don't get z14 directly (unless your metapyramids will have variable zoomlevels). If correctly implemented, all the processes could insert into the same SQLite. We do that with MapTiler - details can be provided on request.

> The reason for metapyramids is that Postgres could more efficiently reuse cache if you query data in similar regions - and some of the vectors are going to be exactly the same in SQL - if you render the tiles above eachother.

**Comment by lukasmartinelli** [comment]
First tests for the world have been concluded. Some notes (mostly for myself).

Interesting:
1. For zoom level 0 to 9 PostgreSQL is the bottleneck with most queries taking quite a long time
2. After that Mapnik takes most of the CPU while PostgreSQL still has to do alot of work
3.  The throughput is heavy. Just to render from z0 to z10 it streams 3.3 TB of data from PostgreSQL to the Mapnik container. For z11 half way through it is already additional 5 TB.

Tiles from zoom level 10 on are much faster to generate but still require alot of throughput and CPU time.

We now use https://github.com/mojodna/tl for generating the MBTiles which is the  `async.parallel` feature. This actually utilizes the CPU capacity very well (100% usage).

Timings:

To generate the entire planet from zoom level 0 to zoom level 10 it takes `21 hours and 55 minutes`.
Of these `1398018` tiles `1024566` tiles (73% -> matches pretty close with the 71% of earth water coverage) contain no data at all.

On average the renderer using 3 cores or approx. 8 AWS ECU processed 17 tiles per second.
On the second experiment where I tried to render z11 to z12 (but stopped) average was 17 tiles per second as well. So after z10 I guess one can estimate 17 tiles per second (using approx. 8 ECU).

**What needs to happen to render the world until zoom level 14?**
Alot actually. At z14 we have to render 358 million tiles which takes `358 million / (17 per second)` -> `243 days` - for z13 it would be `60 days`. I guess the speed will increase much more as there are more and more *zero data* tiles at lower zoom levels so this is quite a wild guess. But it will definitly take a long long time for the lower zoom levels and the sheer amount of data volume passing through the containers is already a challenge in distributing this system.

**The whole process has to be massively parallized if we want to achieve the goal of producing vector tiles for the world at z14.** And this means PostGIS still needs to be able to keep up. At the end we perhaps even need to run several PostGIS servers serving several renderers.

Notes for myself:

Get zero tiles: `cat export.logs | cut -d $'\t' -f2 | grep -Fx  "0" | wc -l`
Calc sum of all tiles: `cat export.logs | cut -d $'\t' -f1 | grep '/' | wc -l`
-> for z10 it should be the same as `4^10+4^9+4^8+4^7+4^6+4^5+4^4+4^3+4^2+4^1`

**Comment by lukasmartinelli** [comment]
Comments to Petr.

> To render cca 358 millions of tiles (1 + 4 + 16 + 64 + 256 + 1024 + 4096 + 16384 + 65536 + 262144 + 1048576 + 4194304 + 16777216 + 67108864 + 268435456 = 357913941) you could start the tasks with defined parallelism.

I like the metapyramid idea for partitioning the work into tasks.

> I believe that if we can get rid of HTTP and crawling of the tiles from localhost web-server, and instead call the mapnik library directly

The tilelive module is using Mapnik directly via the Node bindings (no crawling or HTTP involved), there is no much overhead (since most work is IO related anyway).

> If correctly implemented, all the processes could insert into the same SQLite. We do that with MapTiler - details can be provided on request.

We probably even need to generate multiple MBTiles and merge them together (since we probably have to go multi-host), rather than inserting in parallel. The `landez` library looks very promising for tasks like that and `mbutil` provides a patch utility as well.

**Comment by lukasmartinelli** [comment]
Ideas for solving the parallelizing problem:

**Split the world up in multiple databases each serving multiple local renderers.**

We probably have to do work on multiple hosts with this amount of data and network throughput of that many TBs of data is not the best.

**Create fat vector tiles at z13 and skip z14**

Perhaps by packing much more data into z13 instead of z14 and z15 we can overzoom much mure and it is probably faster for generating the mbtiles (although rendering the rasters will be slower).

**Comment by klokan** [comment]
My notes to the ideas:

**paralelisation**
Agree on horizontal scaling. We may probably need to prepare a virtual machine image (docker + PostGIS data) so each machine has it's own copy of **complete database** - to ensure PostGIS is not the bottleneck. The partitioning with metapyramid makes sense esp. on lower zoom-levels. Upper zoomlevels (z0 to z8 for example) may be done in a single task quite easily.
Having perfect datastyle in #25 quite soon is critical - any change later on implies need to re-render all the tiles again!
BETA has as a deliverable MBTiles of Switzerland #9 - ideally done the way we want to do the world as well later on. It is a great test for the parallelisation.
OK about the multiple MBTiles as results. Maybe ATTACH command can be used in SQLite3 to virtually merge multiple SQLite files together - for testing or even copying to a different final file in post-processing.

**z14 required:**
There is a limit of 500KB per tile defined by MapBox Studio - larger tiles may be refused (probably for a good reason). I am afraid z14 is required - even there it may be challenging to fit all the information and manage the less then 500 KB condition.
For our datastyle is probably easiest is to reverse-engineer the MapBox and follow 1:1 what they did.

MapBox Streets V5 has max z14 - let's target compatibility with V5 in #25
MapBox Streets V6 has max  z15

**empty tiles**
To eliminate the need for empty ocean tiles check: "maskLevel tiles" at https://github.com/mapbox/tilelive-vector

**Comment by lukasmartinelli** [comment]
Answers from Robert Nordan which are relevant for this topic.

### Is the process you have used with Tilelive.js documented somewhere?

> The presentation is probably the best documentation I’ve written! (The video files should be uploaded by FOSS4G soon so you can hear what I said as well..) Since it’s been a part-time project here at work, things have been pretty fragmented and hacky. I wish I had a better answer.

### How much time the rendering of Noway from your own data took?

> We’ve had some database trouble and I’ve had to do other (paying) work, so I haven’t been able to do all of Norway in full detail yet. But I did some tests with a subset of data and zoom levels up to 16 on a i7 desktop machine with 8 cores, connected to a rather weak database server. There it took around five days running in the background without any optimization to do all of Norway at Z16. It spread the work well over all the cores, and RAM usage was never very high, so I think the main issue was waiting on the database server. That was with a scanline method, some later tests down to level 14 (which is done in a matter of hours) showed that pyramids worked better for Norway. I think you can probably improve on these numbers quite a lot if you optimize all the stages properly!

### Could you please describe a bit more how you parallelised the vector rendering?

> The parallelization was very simple: I used the tilelive.copy command (https://github.com/mapbox/tilelive/blob/5a968955510415edd5dc981592c2d88c95469758/bin/tilelive-copy#L30) without any concurrency options. That sets tilelive to use all the available cores (https://github.com/mapbox/tilelive/blob/master/lib/stream-util.js#L1) , which worked well on my desktop. However, I suspect that using it on a server with 24 cores has overwhelmed my database, so you should probably experiment with different values until you find the setting that gives maximum throughput before you try doing really big jobs.

### What storage system (MBTiles, key/value store, directory, SQL database) have you used for the vector tiles?

> I’ve simply exported them to mbtiles using tilelive, which was quick and easy and lets me upload them to mapbox. I have noticed that mbtiles being an SQLite DB doesn’t parallelize so great, so for the whole world you might want to look into other options. I know that mapbox uses serialtiles internally, though I don’t really know how exactly they use them.

### What hardware infrastructure?

> As I’ve described, it’s been a bit of this and a bit of that. But in general I would say you need the same kind of hardware that you would use to render traditional tiles. Good I/O speeds are important, when I tried writing tiles to a traditional hard drive instead of an SSD it went a lot slower.

### Is there are GitHub repo for the toolset you have used to produce vector tiles - so it can be reproduced?
 
> We don’t have a GitHub repo because all the code is rather messy and refers to a lot of internal stuff like our SLD style rules and database schemas which are sadly proprietary. I would like to clean it up, make it independent and put it out there, but don’t have time right now.
