### ISSUE TITLE
OSM2VectorTiles Docker

### ISSUE THREAD

**Issue by lukasmartinelli** [geometalab/osm2vectortiles#3]
Takes OSM Planet files and source style to produce vector mbtiles.

Subtasks:
- #6 Improve OSMBright TM2Source
- #18 Setup PostGIS and Imposm and automated import 
- Set up Mapnik and Tilelive (https://github.com/mapbox/tilelive)
(Very nice post about Mapnik http://mike.teczno.com/notes/mapnik.html)
- Good step by step tutorial to build tileserver -> https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/ there is also already a docker container based on this tutorial -> https://hub.docker.com/r/openfirmware/postgres-osm/

Command for headless export of mbtiles: (path must be absolute)
npm install -g mapnik mbtiles tilelive tilelive-bridge
tilelive-copy --bounds=-180,-85,180,85 bridge:///home/mapbox/tmp/project.tm2source/data.xml mbtiles:///tmp/out.mbtiles

**Comment by lukasmartinelli** [comment]
Perhaps this is something worth looking into:
https://github.com/systemed/tilemaker

If tilemaker can already export vector tiles from OSM that are well suited for applying an OSM bright visual style later on, it would make live much easier because it is a single binary without the stack.

**Comment by klokan** [comment]
TileMaker puts everything into RAM and does not use Mapnik to define the styles. So, it seems it will never be able to render whole world OSM planet and it would be hard to modify for custom Mapnik styles (only with coding in lua). I think this is not a good idea...

**Comment by klokan** [comment]
The FOSS4G presentation mentioned in #2 recommends on 15:10 time solution which is most straighforward probably for the first implementations.
If a single binary should be used then ideally something like: https://github.com/vross/vector-tiles-producer (as mentioned in #13)

**Comment by lukasmartinelli** [comment]
> TileMaker puts everything into RAM and does not use Mapnik to define the styles. So, it seems it will never be able to render whole world OSM planet and it would be hard to modify for custom Mapnik styles (only with coding in lua). I think this is not a good idea...

Didn't know this. Let's start with the proposed approach from the video.
