### ISSUE TITLE
Compare imposm with osm2pgsql

### ISSUE THREAD

**Issue by lukasmartinelli** [geometalab/osm2vectortiles#30]
Currently running an osm2pgsql import of Europe for comparison.
Public benchmarks indicate imposm3 is at least 3x times faster.

If osm2pgsql is not too slow it might be an option for use with the kartotherian tm2source, which would mean less work for creating the vector tiles at the cost of longer import and generation (because tables are no longer generalized etc.) time.

**Comment by sfkeller** [comment]
If this is feasible, try also to compare and evaluate the output. I've seen reports which indicate that there are differences, e.g. that osm2pgsql recognized more buildings than similar programs.

**Comment by klokan** [comment]
@sfkeller are these reported issues documented somewhere, or is it a bug of imposm tracked under some ticket? Is the problem related to imposm3 which is used here or to an old version of imposm?

@lukasmartinelli I really like the idea of having vector tileset truly compatible with MB Streets as it gives a lot of practical benefits...

I wonder why wikimedia people in kartotherian project uses osm2pgsql?
Have you been in touch with them?

After @lukasmartinelli tests the Kartotherian workflow #28 we may need to make the definitive decision if imposm3 or osm2pgsql, and if to commit to our own improved tm2source with all (almost) unmodified visual styles (both Mapnik and GL) or wikipedia's tm2source with only single style now (fork of OSM-Bright).

If the diff updates runs fine with imposm3 - then it seems to me that there are benefits.
Imposm3 was also used in the Alpha milestone.

If imposm3 is confirmed, then @manuelroth (?) should probably start to work actively on improvements of the [tm2source](https://github.com/geometalab/osm2vectortiles/tree/master/osm-bright-2.tm2source) and compatibility with MapBox Streets as defined in #25 to be finished BETA milestone (by November 16th latest).

**Comment by sfkeller** [comment]
@klokan These are not yet specific issues in osm2pgsql or impost - just different interprations of how OSM data and its tags are being interpreted.

**Comment by klokan** [comment]
@sfkeller could you please provide a link to a report which mentions the difference in tags interpretation causing the recognision of less buildings during the import - to have a real example to look for in the OSM data?

So far everything speaks for imposm3.

**Comment by sfkeller** [comment]
It was a comparison of osm2pgsql versus ogr2ogr:
https://lists.osgeo.org/pipermail/qgis-user/2014-May/027473.html
And ogr2ogr was slightly "better" in interpreting OSM data.

**Comment by lukasmartinelli** [comment]
Answer from Yuri from Kartotherian.

**Why did you choose osm2pgsql and how are the query times for producing the vector tiles?**

> We chose osm2pgsql because it is well established and because it can generate the list of invalidated tiles - this way we can regenerate tiles that have been changed. We have been thinking about other options, but for now we will probably stay with osm2pgsql. The initial PBF import runs about 12 hours, after which we will only import the changes, which should be very fast.

**Comment by lukasmartinelli** [comment]
Answer from Max from Kartotherian.

**Why did you choose osm2pgsql and how are the query times for producing the vector tiles?**

> imposm2 doesn't support replication, which is a showstopper for us. imposm3 is not yet production ready, and was even more raw when we were making our decisions. Having stock Debian packages for osm2pgsql/osmosis is also extremely nice.

**Comment by lukasmartinelli** [comment]
Decision has been made.

**Comment by sfkeller** [comment]
Just as an input: Did you see these slides/info from mapsquare.io? Website http://www.mapsquare.io/#/techres/openSource and http://fr.slideshare.net/LoicOrtola/openstreetmap-tileserver-in-one-minute ?
