### ISSUE TITLE
OSMBright TM2Source 

### ISSUE THREAD

**Issue by klokan** [geometalab/osm2vectortiles#4]
Install and try the existing TM2Source projects for OSM-Bright:

https://github.com/search?utf8=%E2%9C%93&q=osm+bright+tm2source&type=Repositories&ref=searchresults

Most advanced seems to be:
https://github.com/mystand/osm-bright-2.tm2source

Try it in MapBox Studio against your imported data in PostGIS database.

Use the existing imposm-mapping.py.

In the later process, the original mapping should be improved. #6

Use the existing OSMBright style when possible:
https://github.com/mapbox/mapbox-studio-osm-bright.tm2

**Comment by lukasmartinelli** [comment]
Explanation of TM2Source:

Mapnik style produces PBFs. You don't care about the look at feel, you care about what is available at which zoom level. XML of Mapnik (Style) to define the layers.

**Comment by klokan** [comment]
The [wiki maps](https://maps.wikimedia.org/) mentioned also in #13 seems to be powered by OSMBright:
https://github.com/kartotherian/osm-bright.tm2
https://github.com/kartotherian/osm-bright.tm2source

This may be worth trying - including their software stack - to compare with other alternatives.
Adjustments required - especially to prepare vtiles into MBTiles efficiently, and if possible stop at upper zoom-levels like 14 and overzoom on drawing only.

**Comment by klokan** [comment]
Anybody looking on Google for the OSMBright TM2Source check our open-streets.tm2source at:
https://github.com/geometalab/osm2vectortiles/
