### ISSUE TITLE
VTileServer Docker

### ISSUE THREAD

**Issue by lukasmartinelli** [geometalab/osm2vectortiles#5]
Tile server takes mbtiles and visual styles and serves PNG/JPG to WSG clients or browser.

Components inside server:
- Mapnik
- Apache
- mod_tile
- mod_renderd

Existing images:
- https://hub.docker.com/r/mguentner/renderd-osm/
- https://hub.docker.com/r/openfirmware/postgres-osm/

Mapnik needs to be compiled with module: https://github.com/mapbox/mapnik-vector-tile and the first version would render and style the sample data from #1

**Comment by klokan** [comment]
The implementation with tesssara exists now.
Let's compare it with mod_renderd.

**Comment by lukasmartinelli** [comment]
Answer from Yuri from Kartotherian to this question.

**Tilelive vs native Mapnik**

From what we know you use tilelive to create the vector tiles which uses node-mapnik under the hood. Do you think calling the code from Node causes much overhead?

An other alternative would be to use mod_renderd and mod_tile as Apache modules to generate the raster tiles directly with Mapnik without any Node code in between. We hope to gain performance from this approach, but we don’t see any examples of people doing this and it seems we would have to compile a custom Mapnik version. Any advice on that?

> This is how OSM was built - everyone has been using mod_renderd + mod_tile.  But, most experts have told us that this approach has no future. Generating raster images do not scale for high DPI devices, require large infrastructure for image caching, cannot easily support multiple languages, cannot be easily re-styled, and many other problems. That's why Mapbox has implemented vector tiles in Mapnik, and that's why they are switching to WebGL in-browser rendering instead of the raster. Moreover, there has been some conversations about switching osm.org to Kartotherian as well.

> Yes, implementing everything in Assembler can always be made faster than in C++, and C++ can be made faster than Node.  The problem is, as always - resources. The time required to make the entire system in C++ is too costly, and would produce results that are not that different from nodejs. Since we are using an extremely efficient caching layer in front of the nodejs servers, plus good SSD disks, we don't think that saving a few extra CPU milliseconds will make a large difference. On the other hand, the nodejs flexibility allowed us to implement the whole system in a few months using ready-made components, something that we could have never achieved with C++. Plus, the system is extremely easy to maintain since our code is less than 10 small files.

**Comment by lukasmartinelli** [comment]
Answer from Max from Kartotherian to this question.

Tilelive vs native Mapnik

From what we know you use tilelive to create the vector tiles which uses node-mapnik under the hood. Do you think calling the code from Node causes much overhead?

> Node is just plumbing, all the heavy stuff is done in native code.

An other alternative would be to use mod_renderd and mod_tile as Apache modules to generate the raster tiles directly with Mapnik without any Node code in between. We hope to gain performance from this approach, but we don’t see any examples of people doing this and it seems we would have to compile a custom Mapnik version. Any advice on that?

> By mod_renderd you mean renderd? Standard OSM stack has a load of problems which resulted in its maintenance-only development and slow dying out:
* It does not scale.
* Cache misses result in slowwww metatile generation on the fly.
* No vector support.
* High storage requirements.

**Comment by klokan** [comment]
BTW we work on improved tessera: https://github.com/klokantech/tileserver-tessera/issues on docker hub at https://hub.docker.com/r/klokantech/tileserver-tessera/

It should be used on announcement of this project - will give people the same sample viewers (but with a new colors / branding for osm2vector tiles), static maps api, etc.

**Comment by lukasmartinelli** [comment]
> BTW we work on improved tessera: https://github.com/klokantech/tileserver-tessera/issues on docker hub at https://hub.docker.com/r/klokantech/tileserver-tessera/

I will set up a raster tile server on Switch infrastructure based on the forked tessera version.

You still recommend hosting the vector tiles with tileserver-php?
Or should we use tessera, because MBTiles serving is fixed in tessera now.
